New Feature: Language Selection
assafelovic/gpt-researcher pull request #142
Opened 2023-08-20 10:56 UTC by jlcases

Greetings,

I've developed an enhanced feature for multi-language support:

Language Selection: This feature provides the capability to select from up to 7 different languages.
<img width="1274" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/69396384/25bc4164-95a7-4264-a44b-5cb2610c7f79">

Language Selection Interface

Optimized Queries: I've implemented a total of 8 queries - 4 in English and 4 in the user-selected language to enhance search results.

Localized Reports: The system now generates reports in the user-selected language.
<img width="1062" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/69396384/e89af502-2740-477a-8173-a1dd3ced452b">

Report Interface

I believe this feature will greatly benefit the project by offering more versatility to users. I'm eager to contribute this to the main repository and am open to any suggestions or modifications you might have.

Thank you for considering my contribution.

Best regards,
Jose Luis Cases

2023-09-07 10:16 UTC, ill-yes requested changes
Looks good! But please write comment in code in english.

2023-10-06 11:16 UTC, notvicent3 reviewed
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_agent_role_prompt(agent, language):
touché

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +        language (str): The language in which the answers should be provided.
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +        "Finance Agent": f"You are a seasoned finance analyst AI assistant. Your primary goal is to compose comprehensive, astute, impartial, and methodically arranged financial reports based on prov
Habría que adaptarlo (si es que ha cambiado a los prompts iniciales) pero Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +    return prompts.get(agent, f"No such agent. All answers must be in {language}.")
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_report_prompt(question, research_summary,language):
Touché. No sé realmente si la falta del espacio de research_summary, language): 
Cambiaría más allá de estética.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_search_queries_prompt(question, language):
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +    return f'For the topic "{question}", list 4 search queries in English and 4 in {language}.'
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_resource_report_prompt(question, research_summary, language):
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_outline_report_prompt(question, research_summary,language):
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +            'an outline in {language} for a research report in Markdown syntax'
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +    return (f'"""{research_summary}""" Using the above information, generate in {language}, '
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +def generate_lesson_prompt(concept,language):
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/prompts.py
> +    prompt = f'generate  a comprehensive lesson in {language} about {concept} in Markdown syntax. This should include the definition'\
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/research_agent.py
> +        self.language = language  # New field for language
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/research_agent.py
> +        self.agent_role_prompt = agent_role_prompt if agent_role_prompt else prompts.generate_agent_role_prompt(agent, self.language)
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/research_agent.py
> +        result = await self.call_agent(prompts.generate_search_queries_prompt(self.question,self.language))
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/research_agent.py
> +        await self.websocket.send_json({"type": "logs", "output": f"🧠 I will conduct my research based on the following queries: {queries}..."})
Deberíamos pensar en introducir la interacción en el language seleccionado también. Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/research_agent.py
> +        answer = await self.call_agent(report_type_func(self.question, self.research_summary, self.language), stream=True, websocket=websocket)
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/run.py
> +        report, path = await run_agent(task, report_type, agent, agent_role_prompt,language,websocket)
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/run.py
> +    async def start_streaming(self, task, report_type, agent, agent_role_prompt, language, websocket):
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/run.py
> +async def run_agent(task, report_type, agent, agent_role_prompt, language, websocket):  # New field for language
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on agent/run.py
> +    assistant = ResearchAgent(task, agent, agent_role_prompt, language, websocket)  # Pasar el idioma al constructor del agente
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on client/index.html
> +            <label for="language" class="agent-question">Select the output language for the report:</label>
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on client/scripts.js
> +        const language = document.getElementById("language").value;  // get language from dropdown
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on client/scripts.js
> +          language: language  // add language to request data
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on main.py
> +    language: str  # New fiedl for language
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on main.py
> +                language = json_data.get("language")  # New field for language
Touché.

2023-10-06 11:16 UTC, notvicent3 commented on main.py
> +                    await manager.start_streaming(task, report_type, agent, agent_role_prompt, language, websocket) # New field for language
Touché.

2023-10-13 12:57 UTC, assafelovic commented
Languages are by default when using most LLMs so selecting the lang is redundant.

2024-05-13 06:07 UTC, assafelovic commented
@saccohuo definitely in demand but very old and many conflicts. Should we open a new PR for this? What ever you decide and happy to help and push this to production! @jlcases

2024-06-05 13:52 UTC, Gallisatyricon commented
I would love to get this function. English is always coming out of the queries, even when the input is a long phrase in another language. Tks in advance if this becomes possible.

2024-12-16 11:15 UTC, tisDDM commented
Is anybody working on this topic? 
If it is stale and it is still wanted I will give it a go, because I also need results in two non-English languages.

GPTR unfortunately is reverting many times into writing English reports, which makes it very uncomfortable for international use.

2024-12-17 06:49 UTC, assafelovic commented
@tisDDM @Gallisatyricon happy to update I've just pushed a fix for languages. Simply export the prefered language as an env var and it should work. For example `export LANGUAGE=spanish`.
Make sure to pull latest!

2024-12-17 06:50 UTC, assafelovic commented
See latest PR here: https://github.com/assafelovic/gpt-researcher/pull/1026

2024-12-17 06:50 UTC, assafelovic commented
Closed, added basic support here: https://github.com/assafelovic/gpt-researcher/pull/1026

2024-12-17 06:50 UTC, closed without merging