Add Docker convenience to run it locally
assafelovic/gpt-researcher pull request #33
Opened 2023-07-12 18:01 UTC by jortegac

Added a `Dockerfile` and a `docker-compose.yml` to make it extra easy to take for a spin. Added instruction on the README on how to do it.

2023-07-12 19:21 UTC, rotemweiss57 approved these changes

2023-07-13 02:43 UTC, rotemweiss57 requested changes
Selenium didn't work properly for some reason, were you able to run it?

2023-07-13 05:02 UTC, jortegac commented
That's a bummer. I can't say I have the same issue, I can run the system and generate reports. 

Did your docker build complete without any issues? It comes to mind to try to have docker image built from scratch

`docker build . --tag assafelovic/gpt-researcher --no-cache`

and then running docker-compose

`docker-compose up`

2023-07-13 07:10 UTC, assafelovic approved these changes

2023-07-13 07:11 UTC, assafelovic approved these changes

2023-07-13 07:11 UTC, assafelovic approved these changes

2023-07-13 07:11 UTC, merged